version: '3.8'

services:
  postgres:
    image: postgres:alpine3.18
    container_name: postgres-container
    restart: always
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      TZ: 'America/Sao_Paulo'
